# Generated by Django 5.1.6 on 2025-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
